In [8]:
import math
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import seed
seed(1)
import pandas as pd
import tensorflow
tensorflow.random.set_seed(1)
from tensorflow.python.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.python.keras.models import Sequential 
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import os 
os.chdir("/scratch/proj/napamegs/mat_out/wavel_random")
h = pd.read_csv("wavel_random4.csv")
#h2= pd.read_csv("wavel_random7.csv")
#h = pd.concat([h1,h2])

df  = h.values
X = df[:,:6]
y= df[:,6:]
#print(y)

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=42)



In [4]:
model = Sequential()
model.add(Dense(32, input_dim=6, kernel_initializer='normal', activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(4, activation='relu'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 32)                224       
_________________________________________________________________
dense_10 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_11 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_12 (Dense)             (None, 4)                 132       
Total params: 4,548
Trainable params: 4,548
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])

In [40]:
diff = 0
mse = 0
sq = 0
a  = Y_test[:,0]
a


array([63.607, 51.607, 47.653, ..., 64.889, 96.56 , 21.91 ])

In [42]:
eepochs = 3
for i in range(eepochs):
    history = model.fit(X_train, Y_train, epochs=1, batch_size=150000, verbose=1)
    pred = model.predict(X_test)
    diff = np.subtract(pred[:,0],a)
    sq  = np.square(diff)
    mse = sq.mean()
    print(mse)


246/246 [==============================] - 19s 75ms/step - loss: 650.4660 - mse: 650.4660 - mae: 13.0066
[[63.431828 62.50967  32.558666 -0.      ]
 [53.868706 54.65726  51.34768  -0.      ]
 [53.13808  55.250767 48.32711  -0.      ]
 ...
 [54.663105 54.430717 47.49206  -0.      ]
 [87.6223   86.400505 11.957855 -0.      ]
 [23.846693 24.01425  73.91113  -0.      ]]
38.5649360327115
246/246 [==============================] - 19s 77ms/step - loss: 648.8162 - mse: 648.8162 - mae: 12.8905
[[65.75888  64.72856  31.507336 -0.      ]
 [56.503277 57.310196 49.940506 -0.      ]
 [56.194046 58.156166 46.241695 -0.      ]
 ...
 [56.05222  55.77687  46.79063  -0.      ]
 [89.07957  87.8118   11.430333 -0.      ]
 [25.262165 25.212261 73.976616 -0.      ]]
36.934974710065724
246/246 [==============================] - 20s 82ms/step - loss: 648.5291 - mse: 648.5291 - mae: 12.8915
[[63.16277  62.235767 31.80241  -0.      ]
 [54.357002 55.44583  49.74061  -0.      ]
 [54.274963 56.162975 45.699005 -0.

In [36]:
pred = model.predict(X_test)

KeyboardInterrupt: 

In [ ]:
for i in range(epochs)

In [34]:
predictions = model.predict(X_test)
model.save("MODEL_2")

KeyboardInterrupt: 

In [ ]:
predictions

array([[88.86018 , 85.39195 , 29.20727 , -0.      ],
       [38.631092, 39.459408, 70.46346 , -0.      ],
       [53.62804 , 52.942055, 71.67458 , -0.      ],
       ...,
       [42.379414, 43.437424, 24.60053 , -0.      ],
       [54.28708 , 53.820454, 11.656485, -0.      ],
       [18.879658, 17.968918, 73.98479 , -0.      ]], dtype=float32)

In [ ]:
predictions[:,0]

array([88.86018 , 38.631092, 53.62804 , ..., 42.379414, 54.28708 ,
       18.879658], dtype=float32)

In [ ]:
Y_test

array([[63.607, 63.607, 36.29 , 36.29 ],
       [51.607, 51.607, 48.144, 48.144],
       [47.653, 47.653, 52.153, 52.153],
       ...,
       [64.889, 64.889, 34.917, 34.917],
       [96.56 , 96.56 ,  3.328,  3.328],
       [21.91 , 21.91 , 77.724, 77.724]])

In [ ]:
diff_arrau = np.subtract(Y_test[:,0],predictions[:,0])
sm = np.square(diff_arrau)
mse = sm.mean()
print(mse)


226.19492944115976


SyntaxError: unexpected EOF while parsing (<ipython-input-27-281e865874b4>, line 1)

In [ ]:
# summarize history for accuracy
plt.plot(history.history['mae'])
plt.title('MAE LOSS VARIATION')
plt.ylabel('value')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
plt.plot(history.history['mse'])
plt.title('MSE LOSS VARIATION')
plt.ylabel('value')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()


In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
import os 
from sklearn.tree import DecisionTreeRegressor 
from sklearn import tree
import graphviz 
import matplotlib.pyplot as plt
import matplotlib.image as pltimg 
from sklearn.tree import export_graphviz 
os.chdir("/scratch/proj/napamegs/all_data/Ag/Ag_n3.1/")
# reading the csv files 
h0 = pd.read_csv("TRS_5.csv")
h1 = pd.read_csv("TRS_10.csv")
h2 = pd.read_csv("TRS_15.csv")
# combining TRS_0.csv and TRS_2.csv file
h = pd.concat([h0,h2])
# splitting into training  set
x_train  = h.iloc[:,4:8] 
y_train = h.iloc[:,8:12]
# splitting the testing set
x_test = h1.iloc[:,4:8]
y_test = h1.iloc[:,8:12]
# build DT model and finetune
rt = DecisionTreeRegressor(criterion = 'mse',max_depth = 4)
# Training the DT model
model_r = rt.fit(x_train,y_train)
# Test DT model 
y_pred = model_r.predict(x_test)
feature = ['height','rad','gap']

fig = plt.figure(figsize=(15,15))
_ = tree.plot_tree(rt, feature_names=feature, filled=True)

ModuleNotFoundError: No module named 'graphviz'

In [ ]:
# implement multiple loss
import torch
import pandas as pd
# Importing the Boston Housing dataset
from sklearn.datasets import load_boston
# Loading the Boston Housing dataset
boston = load_boston()
# Initializing the dataframe
data = pd.DataFrame(boston.data)
data.head()
import math
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import seed
seed(1)
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf 
import tensorflow
tensorflow.random.set_seed(1)
from tensorflow.python.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.python.keras.models import Sequential 
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import os 
%matplotlib inline
os.chdir("/scratch/proj/napamegs/mat_out/wavel_random")
h = pd.read_csv("wavel_random4.csv")
#df  = h.values
#X = df[:,:6]
#y= df[:,6:]

# Split the data into train and test with 80 train / 20 test
train,test = train_test_split(h, test_size=0.2, random_state = 1)
train,val = train_test_split(train, test_size=0.2, random_state = 1)
# Helper functions
def norm(x):
    return (x - train_stats['mean']) / train_stats['std']
def format_output(data):
    y1 = h.pop('T_s')
    y1 = np.array(y1)
    y2 = h.pop('T_p')
    y2 = np.array(y2)
    y3 = h.pop('R_s')
    y3 = np.array(y3)
    y4 = h.pop('R_p')
    y4 = np.array(y4)
    return y1, y2,y3,y4
#from sklearn.model_selection import train_test_split
#X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(len(X_train.columns))
def build_model():
    # Define model layers.
    input_layer = Input(shape=(len(train .columns),))
    first_dense = Dense(units='128', activation='relu')(input_layer)
    # Y1 output will be fed from the first dense
    y1_output = Dense(units='1', name='price_output')(first_dense)
    second_dense = Dense(units='128',activation='relu')(first_dense)
    # Y2 output will be fed from the second dense
    y2_output = Dense(units='1',name='ptratio_output')(second_dense)
    # Define the model with the input layer 
    # and a list of output layers
    model = Model(inputs=input_layer,outputs=[y1_output, y2_output])
return model
import torch

outp1 = torch.randn(2, 5)
outp2 = torch.randn(2, 5)
indexes = torch.tensor([0,1,2])

spec1 = outp1.index_select(dim=1, index=indexes)
spec2 = outp2.index_select(dim=1, index=indexes)


print("Output1: \n%s\n" % outp1)
print("Output2: \n%s\n" % outp2)
print("Selected1: \n%s\n" % spec1)
print("Selected2: \n%s\n" % spec2)
outp1 = model1(inputs) # is of shape (batch_size, 100)
outp2 = model2(inputs)

indexes = torch.tensor([0,1,2,3])

spec1 = outp1.index_select(dim=1, index=indexes) # Selects nodes at indexes over the whole batch
spec2 = outp2.index_select(dim=1, index=indexes)
import resource
import signal
import time
def time_expired(n, stack):
    print('EXPIRED :', time.ctime())
    raise SystemExit('(time ran out)')
def set_cpu_runtime():
    # Install the signal handler and set a resource limit
    soft, hard = resource.getrlimit(resource.RLIMIT_CPU)
    print('Soft limit starts as  :', soft)
    resource.setrlimit(resource.RLIMIT_CPU, (10, hard))
    soft, hard = resource.getrlimit(resource.RLIMIT_CPU)
    print('Soft limit changed to :', soft)
    signal.signal(signal.SIGXCPU, time_expired)
set_cpu_runtime()
# Performing a CPU intensive task
print('Starting:', time.ctime())
for i in range(300000):
    for j in range(220000):
        _ = i * j
# Will not be able to execute this!
print('Exiting :', time.ctime())
! expect -c 'spawn ssh gpu-login@param-ishan.iitg.ac.in; expect "password:"; send "abc@123\r"; interact'
import paramiko
host = "172.17.0.8"
port = 22
username = "napamegs"
password = "abc@123"

command = "ls"

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(host, port, username, password)

stdin, stdout, stderr = ssh.exec_command(command)
lines = stdout.readlines()
print(lines)
! ifconfig

model = Sequential()
model.add(Dense(32, input_dim=6, kernel_initializer='normal', activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(4, activation='linear'))
model.summary()
model.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])
history=model.fit(X_train, Y_train, epochs=1, batch_size=2000, verbose=1, validation_split=0.2)


